easy_admin:
    site_name: Allo Zoe Admin
    formats:
        datetime:   'd/m/Y à H\hi e'
        date:       'd/m/Y'
        time:       'H\hi e'
    entities:
        Restaurant:
            class: App\Entity\Restaurant
            label: "Restaurants"
            list:
                actions: ['-delete']
                fields:
                    -
                        property: id
                        label: ID
                    -
                        property: name
                        label: Nom
                    -
                        property: address
                        type: Adresse
                    -
                        property: city
                        label: Ville
                    -
                        property: status
                        label: Statut
                        type: toggle
            form:
                fields:
                    -
                        property: name
                        label: Nom
                    -
                        property: description
                        label: Description
                    -
                        property: imageFile
                        type: vich_image
                    -
                        property: address
                        label: Adresse
                        type_options:
                            required: true
                    -
                        property: cp
                        label: Code postal
                        type_options:
                            required: true
                    -
                        property: city
                        label: Ville
                        type_options:
                            required: true
                    -
                        property: owner
                        label: Propriétaire
                    -
                        property: restaurantSpecialities
                        label: Menus spécialités
                    -
                        property: status
                        label: Status
        User:
            class: App\Entity\User
            label: "Utilisateurs"
            #role: ROLE_SUPER_ADMIN
#            permissions:
#                list:  ['ROLE_SUPER_ADMIN', 'ROLE_EDITOR']
#                create:  ['ROLE_SUPER_ADMIN']
#                edit:  ['ROLE_SUPER_ADMIN', 'ROLE_EDITOR']
#                delete:  ['ROLE_SUPER_ADMIN']
            form:
                fields:
                    -
                        property: username
                        label: Nom d'utilisateur
                    -
                        property: firstname
                        label: Prénom
                    -
                        property: lastname
                        label: Nom
                    -
                        property: email
                        label: Email
                    -
                        property: phone_number
                        label: Téléphone
                    -
                        property: address
                        label: Adresse
                    -
                        property: password
                        label: Mot de passe
                        type: password
                        
                    -
                        property: latitude
                        label: Latitude
                    -
                        property: longitude
                        label: Longitude
                    -
                        property: roles
                        label: Role
                        type: choice
                        type_options:
                            expanded: true
                            choices: { 'Client': 'ROLE_CLIENT', 'Administrateur': 'ROLE_RESTAURANT', 'Livreur': 'ROLE_DELIVER' }
            list:
                fields:
                    -
                        property: id
                        label: ID
                    -
                        property: username
                        label: Pseudonyme
                    -
                        property: firstname
                        label: Prénom
                    -
                        property: lastname
                        label: Nom
                    -
                        property: email
                        label: Email
                        type: email
                    -
                        property: phoneNumber
                        label: Téléphone
                    -
                        property: roles
                        label: Roles
            edit:
                fields:
                    - '-roles'
                    -
                        property: password
                        type: password
                        label: Mot de passe
                        type_options:
                            required: false
                    
                        
        Client:
            class: App\Entity\User
            list:
                dql_filter: "entity.roles LIKE '%%ROLE_CLIENT%%'"
            form:
                fields:
                    -
                        property: username
                        label: Nom d'utilisateur
                    -
                        property: firstname
                        label: Prénom
                    -
                        property: lastname
                        label: Nom
                    -
                        property: email
                        label: Email
                    -
                        property: phone_number
                        label: Téléphone
                    -
                        property: address
                        label: Adresse
                    -
                        property: password
                        label: Mot de passe
                        type: password
                    -
                        property: latitude
                        label: Latitude
                    -
                        property: longitude
                        label: Longitude
            edit:
                fields:
                    -
                        property: password
                        label: Mot de passe
                        type: password
                        type_options:
                            required: false
        Deliver:
            class: App\Entity\User
            list:
                dql_filter: "entity.roles LIKE '%%ROLE_DELIVER%%'"
            form:
                fields:
                    -
                        property: username
                        label: Nom d'utilisateur
                    -
                        property: firstname
                        label: Prénom
                    -
                        property: lastname
                        label: Nom
                    -
                        property: email
                        label: Email
                    -
                        property: phone_number
                        label: Téléphone
                    -
                        property: address
                        label: Adresse
                    -
                        property: password
                        label: Mot de passe
                        type: password
                    -
                        property: latitude
                        label: Latitude
                    -
                        property: longitude
                        label: Longitude
            edit:
                fields:
                    -
                        property: password
                        label: Mot de passe
                        type: password
                        type_options:
                            required: false
                
        Admin:
            class: App\Entity\User
            list:
                dql_filter: "entity.roles LIKE '%%ROLE_ADMIN%%'"
            form:
                fields:
                    -
                        property: username
                        label: Nom d'utilisateur
                    -
                        property: firstname
                        label: Prénom
                    -
                        property: lastname
                        label: Nom
                    -
                        property: email
                        label: Email
                    -
                        property: phone_number
                        label: Téléphone
                    -
                        property: address
                        label: Adresse
                    -
                        property: password
                        label: Mot de passe
                        type: password
                    -
                        property: latitude
                        label: Latitude
                    -
                        property: longitude
                        label: Longitude
            edit:
                fields:
                    -
                        property: password
                        label: Mot de passe
                        type: password
                        type_options:
                            required: false
        CategoryMenu:
            class: App\Entity\CategoryMenu
            label: "Catégorie de menu"
            form:
                fields:
                    -
                        property: name
                        label: Nom
                    -
                        property: description
                        label: Description
                    -
                        property: imageFile
                        type: vich_image
                        label: Image
            list:
                title: Catégories / Spécialités
        TypeMenu:
            class: App\Entity\TypeMenu
            label: "Type de menu"
        Menu:
            class: App\Entity\Menu
            label: "Menus"
            disabled_actions: ['delete']
            list:
                actions: ['show', 'edit']
#            form:
#                fields:
#                    -
#                        property: name
#                        label: Nom
#                    -
#                        property: description
#                        label: Description
#                    -
#                        property: price
#                        label: Prix
#                    -
#                        property: imageFile
#                        type: vich_image
        MenuOption:
            class: App\Entity\MenuOption
            label: "Option de menu"
        MenuMenuOption:
            class: App\Entity\MenuMenuOption
            label: "Menu - options"
        Product:
            class: App\Entity\Product
            label: "Produits"
            form:
                fields:
                    -
                        property: name
                        label: Nom
                    -
                        property: price
                        label: Prix
                    -
                        property: restaurant
                        label: Restaurant
                    -
                        property: imageFile
                        type: vich_image
                    -
                        property: status
                        label: Actif
            list:
                title: Produits
                fields:
                    -
                        property: id
                        label: ID
                    -
                        property: name
                        label: Nom
                    -
                        property: price
                        label: Prix
                    -
                        property: status
                        label: Statut
                        type: toggle
                    -
                        property: image
                        type: image
                        base_path: /images/product
                        
        MenuOptionProducts:
            class: App\Entity\MenuOptionProducts
            label: "Options - Produits"
        
        RestaurantSpeciality:
            class: App\Entity\RestaurantSpeciality
            label: "Spécialité des restaurants"
        Order:
            class: App\Entity\Order
            label: "Commandes"
            list:
                actions: [-delete, -new]
        ShippingOrder:
            class: App\Entity\Order
            label: En cours de livraison
            list:
                actions: [-delete, -new]
                dql_filter: "entity.orderStatus = 6"
                title: Commandes en cours de livraison
        ShippedOrder:
            class: App\Entity\Order
            label: Terminée
            list:
                actions: [-delete, -new]
                dql_filter: "entity.orderStatus = 4"
                title: Commandes livrées
                fields:
                    -
                        property: id
                        label: ID
                    -
                        property: ref
                        label: Reférence
                    -
                        property: amount
                        label: Montant
                    -
                        property: date_created
                        label: "Date commande"
                    -
                        property: address
                        label: "Adresse de livraison"
                    -
                        property: AllozoeCommission
                        label: Commission Allozoé
                    -
                        property: RestauEarn
                        label: Revenu restaurant
                    
        NewOrder:
            class: App\Entity\Order
            label: Nouvelles commandes
            list:
                actions: [-delete, -new]
                dql_filter: "entity.orderStatus = 1"
                title: Nouvelles commandes
        ApprovedOrder:
            class: App\Entity\Order
            label: Commandes validées
            list:
                actions: [-delete, -new]
                dql_filter: "entity.orderStatus = 2"
                title: En attente de livreur
        OrderStatus:
            class: App\Entity\OrderStatus
            label: "Statut de commande"
            form:
                fields:
                    -
                        property: name
                        label: Nom
        PaymentMode:
            class: App\Entity\PaymentMode
            label: Mode de paiement
            form:
                fields:
                    -
                        property: name
                        label: Nom
        Ticket:
            class: App\Entity\Ticket
            label: Tickets
        SlideShow:
            class: App\Entity\Slideshow
            label: Slideshow
            form:
                fields:
                    -
                        property: imageFile
                        type: vich_image
                    -
                        property: title
                        label: Titre
                        type_options:
                            required: false
                    -
                        property: subtitle
                        label: Sous-titre
                        type_options:
                            required: false
                    -
                        property: addClasses
                        label: Classes CSS
                    -
                        property: active
                        label: Actif
                        
            
    design:
        form_theme: '%env(APP_TEMPLATE_ADMIN)%%env(DS)%easy_admin%env(DS)%form%env(DS)%bootstrap_3_horizontal_layout.html.twig'
        templates:
            layout: '%env(APP_TEMPLATE_ADMIN)%%env(DS)%easy_admin%env(DS)%main.html.twig'
            menu: '%env(APP_TEMPLATE_ADMIN)%%env(DS)%easy_admin%env(DS)%menu.html.twig'
            list: '%env(APP_TEMPLATE_ADMIN)%%env(DS)%easy_admin%env(DS)%list.html.twig'
        menu:
            -
                label: Utilisateurs
                icon: users
                role: ROLE_SUPER_ADMIN
                children:
                    -
                        entity: User
                        label: Tous
                    -
                        entity: Client
                        label: Clients
                    -
                        entity: Deliver
                        label: Livreurs
                    -
                        route: logged_delivers
                        label: Livreurs connectés
                    -
                        entity: Admin
                        label: Restaurateurs
            -
                entity: Restaurant
                label: Restaurants
                icon: thumb-tack
                default: true
                role: ROLE_RESTAURANT
            -
                entity: Menu
                label: Menus
                icon: cutlery
                role: ROLE_RESTAURANT
            -
                entity: Product
                label: Produits
                icon: shopping-bag
                role: ROLE_RESTAURANT
            -
                entity: CategoryMenu
                label: Catégories / Spécialités
                icon: folder-open
                role: ROLE_SUPER_ADMIN
            -
                label: Commandes
                icon: first-order
                role: ROLE_RESTAURANT
                children:
                    -
                        route: dashboard_o
                        label: Dashboard commandes
                    -
                        entity: NewOrder
                        label: Nouvelles commandes
                    -
                        entity: ApprovedOrder
                        label: Commandes validées
            -
                label: Livraison
                icon: truck
                children:
                    -
                        entity: ShippingOrder
                        label: En cours
                    -
                        entity: ShippedOrder
                        label: Terminées
            -
                entity: OrderStatus
                label: Status de Commande
                icon: smile-o
                role: ROLE_SUPER_ADMIN
            -
                entity: PaymentMode
                label: Mode de paiement
                icon: money
                role: ROLE_SUPER_ADMIN
#            -
#                entity: Ticket
#                label: Tickets restau
#                icon: drivers-license
#                role: ROLE_RESTAURANT
            -
                label: Cartes
                icon: map
                role: ROLE_RESTAURANT
                children:
                    -
                        route: map_delivers
                        label: Livreurs
            -
                label: Configurations
                icon: cog
                route: stripe_config
            -
                label: Slideshow
                icon: desktop
                entity: SlideShow
                    

