vich_uploader:
    db_driver: orm

    mappings:
        products:
            uri_prefix: /images/product
            upload_destination: '%kernel.project_dir%/public/images/product'
        menus:
            uri_prefix: /images/menu
            upload_destination: '%kernel.project_dir%/public/images/menu'
        categories:
            uri_prefix: /images/category
            upload_destination: '%kernel.project_dir%/public/images/category'
        restaurants:
            uri_prefix: /images/restaurant
            upload_destination: '%kernel.project_dir%/public/images/restaurant'
        slideshow:
            uri_prefix: /images/slideshow
            upload_destination: '%kernel.project_dir%/public/images/slideshow'